@startuml
'https://plantuml.com/sequence-diagram

Client -> AuthController: login
AuthController -> AuthController: validateInput
alt validateInput == false
    Client <-- AuthController:
    note right of Client
    {
      "code": "invalid_request",
      "message": "Invalid input provided.",
      "data": null
    }
    end note
end
AuthController -> AuthService: authenticateUser
AuthService -> UserRepository: findByIdentifier
UserRepository --> AuthService: user
alt user == null
    Client <-- AuthService:
    note right of Client
    {
      "code": "resource_not_found",
      "message": "No user is found."
    }
    end note
end
alt user's status == inactive
    Client <-- AuthService:
    note right of Client
    {
      "code": "account_disabled",
      "message": "User's status is inactive."
    }
    end note
end

AuthService -> AuthService: validatePassword
alt password invalid
    Client <-- AuthService:
    note right of Client
    {
      "code": "invalid_credentials",
      "message": "Invalid username or password"
    }
    end note
end
AuthService -> AuthService: generateJWTToken
AuthController <-- AuthService:
Client <-- AuthController:
note right of Client
{
  "code": "success",
  "data": LoginResponse
}

**LoginResponse Schema:**
See: ./resources/openapi/components/LoginResponse.yaml
end note

@enduml